spring.application.name=RaceControl
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3307/race_control?allowPublicKeyRetrieval=true&useSSL=false

spring.datasource.username=ventu
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Productor (El que envía)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumidor (La televisión que escucha)
spring.kafka.consumer.group-id=tv-station-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Gemini
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent
gemini.api.key=AIzaSyAPZbVSR5Gbxf6EkVNgO3ew-04BkjXA2nY

jwt.secret=4f6a7d8b9e0c1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1e2d3c4b5a6